spring:
  application.name: bpm-order-process

  config:
    import: "file:./cluster.yml"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    distribution:
      percentiles:
        camunda.worker.duration: 0.5,0.95,0.99
